### ISSUE TITLE
error after bundle

### ISSUE THREAD

**Issue by jcsky** [Moove-it/swaggard#30]
Rails 5.0.0.rc2
ruby 2.3.1p112

when I add gem 'swaggard' and bundle

error when 'rails s'
/usr/local/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.rc2/lib/action_dispatch/middleware/stack.rb:96:in `push': can't modify frozen Array (RuntimeError)

everything ok when remove gem

error message
```
Exiting
/usr/local/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.rc2/lib/action_dispatch/middleware/stack.rb:96:in `push': can't modify frozen Array (RuntimeError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.rc2/lib/action_dispatch/middleware/stack.rb:96:in `use'
	from /usr/local/lib/ruby/gems/2.3.0/gems/rails_admin-1.1.0/lib/rails_admin/engine.rb:27:in `block in <class:Engine>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc2/lib/rails/initializable.rb:30:in `instance_exec'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc2/lib/rails/initializable.rb:30:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc2/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc2/lib/rails/initializable.rb:54:in `run_initializers'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc2/lib/rails/application.rb:352:in `initialize!'
	from /Users/sky/project/Amazingtutor/config/environment.rb:7:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.rc2/lib/active_support/dependencies.rb:293:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.rc2/lib/active_support/dependencies.rb:293:in `block in require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.rc2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.rc2/lib/active_support/dependencies.rb:293:in `require'
	from /Users/sky/project/Amazingtutor/config.ru:3:in `block in <main>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
	from /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
	from /Users/sky/project/Amazingtutor/config.ru:in `new'
	from /Users/sky/project/Amazingtutor/config.ru:in `<main>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
	from /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
	from /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
	from /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/server.rb:318:in `build_app_and_options_from_config'
	from /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/server.rb:218:in `app'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc2/lib/rails/commands/server.rb:59:in `app'
	from /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/server.rb:353:in `wrapped_app'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc2/lib/rails/commands/server.rb:124:in `log_to_stdout'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc2/lib/rails/commands/server.rb:77:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc2/lib/rails/commands/commands_tasks.rb:90:in `block in server'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc2/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc2/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc2/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/sky/project/Amazingtutor/bin/rails:9:in `require'
	from /Users/sky/project/Amazingtutor/bin/rails:9:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `load'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/client/command.rb:7:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/client.rb:30:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spring-2.0.0/bin/spring:49:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `load'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/sky/project/Amazingtutor/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

**Comment by adrian-gomez** [comment]
Thats just by adding the gem? No initializer?

I'll try that combination of ruby/rails to see if I can reproduce it

**Comment by adrian-gomez** [comment]
@jcsky I was not able to reproduce it. Could you provide me access to the code that fails or build an small sample app where the issue happens?

**Comment by gaukharaya** [comment]
Getting `Bundler could not find compatible versions for gem "rails"` error after bundle install.
ruby 2.1.7
rails 4.1.9
swaggard 0.4.0

**Comment by adrian-gomez** [comment]
@gaukharaya can you share your `Gemfile`? I just tried that setup and it worked fine for me.

What happens if you loose the version restriction for `swaggard`? ie:
```
gem "swaggard"
```
